[project]
name = "cardiovascular-system-heart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipywidgets",
    "jupyter",
    "matplotlib",
    "numpy",
    "pandas",
]

[dependency-groups]
dev = [
    "ipykernel",
    "uv",
]

[tool.uv]
link-mode = "copy"